# Generated by Django 3.1.5 on 2021-01-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210125_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='regid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
