# Generated by Django 3.1.5 on 2021-01-24 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210125_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='regid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
