# Generated by Django 3.1.5 on 2021-01-24 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210125_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 1, 3, 7, 569816)),
        ),
    ]
